PrakashGatiyala/60-seconds-of-cpp

snippets/Reverse words in a given string good first issueGood for newcomers.md

Signed-off-by: anees_19 <aneeskuar@gmail.com>

submission of my work

---

snippets/mergeSort.md

Created a Merge Sort Snippet, Can you have a look at this and if everything is okay, Can you merge it?

Add merge sort Snippet

---

snippets/upper_bound.md

Signed-off-by: Prakash <gatiyalap@gmail.com>

Upper bound STL

---

snippets/lower_bound.md

Signed-off-by: Prakash <gatiyalap@gmail.com>

Lower bound STL

---

snippets/UserInput.md

Hey! I have added the code please verify and merge it. @PrakashGatiyala 
Issue - #19

Added User Input Name Code

---

snippets/operator.md

https://github.com/PrakashGatiyala/60-seconds-of-cpp/issues/47

create operator file

---

snippets/dynamicmemoryallocation.md

https://github.com/PrakashGatiyala/60-seconds-of-cpp/issues/49

added about dynamic allocation memory

---

snippets/mapfunction.md

https://github.com/PrakashGatiyala/60-seconds-of-cpp/issues/51

added about map function and its code in c++

---

snippets/ExceptionHandling.md

https://github.com/PrakashGatiyala/60-seconds-of-cpp/issues/53

added about exception handling and the code in c++

---

snippets/Binomial_coefficient.md

Signed-off-by: Ritesh Kumar <kumarritesh14062000@gmail.com>

Binomial Coefficient

---

snippets/AllFactors.md

I have added code snippets for this program. Please verify and merge it. Thank You! @PrakashGatiyala 
Issue - #45

Added snippets for AllFactors

---

README.md

Fixing typo in README file

---

snippet-template.md
snippets/Passingarray.md

https://github.com/PrakashGatiyala/60-seconds-of-cpp/issues/52

Added passing array to function code in c++

---

snippets/selectionsort.md

Signed-off-by: rithwik003 <amaraneni.rithwik@gmail.com>

Added selectionsort.md file

---

snippets/Check_whether_a_word_is_anagram_or_not.md
snippets/swap_numbers_without_using_temporary_variables.md

Swap Numbers Without Using Temporary Variables solution in c++ with explanation of logic...

Swap Numbers Without Using Temporary Variables solution in c++ 

---

snippets/linkedList.md

Made basic operation of linked list such as deletion ,initialisation , inserting , length ,etc

Basic operation of linked list

---

snippets/Setbit_Count.md

Created SetBit Count

---

snippets/swapnumbers.md

Hey! I have added snippets for swapping numbers. Please verify and merge it.
Issue - #43

Added Swap Numbers code

---

snippets/sort array in c++/bubble_sort.md
snippets/sort array in c++/quick_sort.md
snippets/sort array in c++/simple_sort.md
snippets/sort array in c++/sort_func.md

A folder is added with some algorithm of sorting array in ascending order

sort algo folder added with some snippets

---

snippets/Sort_A_Stack.md

Sorts A Given Stack
Closes #68

Added Sort_A_Stack.md

---

snippets/Decimal-to-Binary.md

Decimal To Binary Conversion Using Bitwise Operator

Created Decimal To Binary

---

snippets/Median Of Sorted Array.md

If we have given a Sorted array of even length then this snippest is helpful to find its median in the least time possible.
This Pull Request is related to issue which was assisned to me please try to merge after 1 october and also u can close the issue and if any modification is suggested let me know:-
#https://github.com/PrakashGatiyala/60-seconds-of-cpp/issues/12

Median of Sorted Array Of Even Length

---

snippets/Binary-to-Decimal.md

Please review and put label as hacktober fest

Added Binary To Decimal

---

snippets/switch_case.md

Switch case

---

snippets/kth_small_element_in_array.md
snippets/reversing_the_integer.md

Signed-off-by: rithwik003 <amaraneni.rithwik@gmail.com>

Added reversing_the_integer.md file

---

snippets/sudokuSolver.md

- A sudoku is generally a 9 by 9 row column grid in which 9, 3 cross 3 sub grids are there. It has some properties associated with it.
- Each 3 cross 3 sub grid has exactly numbers from 1 to 9.
- Each horizontal row has exactly numbers from 1 to 9.
- Each vertical column has exactly numbers from 1 to 9.
- This program uses recursion and backtracking concept to solve partially filled sudoku and finds the correct fully filled sudoku.
- I hope this will be new for you. Just try it.
I have added C++ code for Sudoku. This will facilitate GitHub users when they go through this repository.
I hope this will be a definitely a better contribution and you will merge my pull request.
Kindly add the **hacktoberfest-accepted**  and **approved** labels in this pull request while accepting.
Thanks a lot! …

Added SUDOKU SOLVER C++ CODE

---

snippets/strong_number_in_cpp.md

Signed-off-by: rithwik003 <amaraneni.rithwik@gmail.com>

Added strong_number_in_cpp.md

---

snippets/setPercision.md

Signed-off-by: Prakash <gatiyalap@gmail.com>

SetPercision function for floats

---

snippets/custom_comparator.md

Signed-off-by: Prakash <gatiyalap@gmail.com>

custom comparator for sorting

---

check_Even_or_Odd.md

Hey! Please merge it into your repo. @PrakashGatiyala

Added Check Even or Odd

---

snippets/Dijkstra's_Algorithm.md

Signed-off-by: Trishit Bhowmik <90523629+trishit78@users.noreply.github.com>
If the code is fine, please add this, or if there is any error, please let me know, and I would correct it.
Thank you.

Added Dijkstra's Algorithm
